FROM busybox:1
LABEL maintainer="Manuel Zavatta <manuel.zavatta@gmail.com>"
# @todo scrivere la descrizione completa (aggiornare anche su docker-hub)
LABEL description="Image for my Docker course"
CMD [ "/bin/sh", "-c", "while date; do sleep 1; done;" ]
